### ISSUE TITLE
Anki not work 

### ISSUE THREAD

**Issue by Richard2007-21** [anton-suprun/anki-raycast#5]
When the Anki app is not active, it doesn’t work. Why is that, and how can it be changed? Best regards from Germany, Richard.”

**Comment by anton-suprun** [comment]
Hi @Richard2007-21  

Great question. 

This extension uses a really awesome Anki plugin called [anki-connect. ](https://foosoft.net/projects/anki-connect/)

In order for this Raycast plugin to access Anki application, anki-connect has to be installed and Anki has to be on otherwise it cannot access Anki

I'm exploring other options of access (directly accessing Anki via Anki database) however this involves a lot more work and carries some risks. 


As it currently stands, I don't have plans to add support for this extension to work without Anki being active unfortunately. Sorry about that 


One thing that I do, is have Anki turn on during login (and just have it on in the background at all times for convenience) 

Another option I'm considering is turning on Anki automatically (if it's not already on) when you attempt to access it via this plugin
